import { PtcMfgProcMgmtOperationActionCreateMpmOperationToPartLinksWithOperationPathProcessPlanIdRelatedAssemblyIdProcessPlanNavigationCriteriaIdRelatedAssemblyNavigationCriteriaIdDescription as description } from './description';

export {
	description
};
